export const traducciones = {
  es: {
    idioma: 'ES',
    bandera: '🇪🇸',
    idiomaNombre: 'Español',
    cambiarIdioma: 'Cambiar idioma',
    temaClaro: 'Modo claro',
    temaOscuro: 'Modo oscuro',
    abrirMenu: 'Abrir menú',
    cerrarMenu: 'Cerrar menú',
    buscar: 'Buscar',
    inicio: 'Inicio',
    historias: 'Historias',
    producto: 'Producto',
    comunidad: 'Comunidad',
    tendencias: 'Tendencias',
    creadores: 'Creadores',
    escribir: 'Escribir',
    guardados: 'Guardados',
    avisos: 'Avisos',
    perfil: 'Perfil',
    salir: 'Salir',
    entrar: 'Entrar',
    registrarse: 'Registrarse',
    sesionCerrada: 'Sesión cerrada',
    cookiesTitulo: 'Usamos cookies para mejorar Pixara',
    cookiesTexto: 'Guardamos preferencias básicas, idioma, tema e intereses para ordenar mejor tu experiencia.',
    aceptar: 'Aceptar',
    exploraNuevo: 'Explora lo nuevo',
    masHistorias: 'Más historias nuevas',
    publicar: 'Publicar',
    unete: 'Únete',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    leerAhora: 'Leer ahora',
    empezarAhora: 'Empezar ahora',
    heroEtiqueta: 'Pixara',
    heroTitulo: 'Lecturas sociales con calma, criterio y comunidad.',
    heroTexto: 'Pixara une historias, perfiles, guardados y conversaciones en una experiencia limpia. Descubre autores, publica ideas y crea un feed que aprende de lo que te interesa.',
    escribirAhora: 'Escribir ahora',
    crearCuenta: 'Crear cuenta',
    explorarHistorias: 'Explorar historias',
    heroVisualEtiqueta: 'Historia',
    heroVisualTitulo: 'Ideas que conectan',
    heroVisualTexto: 'Publicaciones, comentarios y guardados en un espacio claro.',
    lecturaSocial: 'Lectura social',
    historiasRecientes: 'Historias recientes',
    verHistorias: 'Ver historias',
    comoFunciona: 'Cómo funciona',
    homeLeeTitulo: 'Lee sin ruido',
    homeLeeTexto: 'Entra, lee, guarda y encuentra autores sin una interfaz pesada ni distracciones innecesarias.',
    homeEscribeTitulo: 'Escribe con contexto',
    homeEscribeTexto: 'Cada publicación tiene título, contenido, etiquetas, conversación y perfil para construir presencia editorial.',
    homeDescubreTitulo: 'Descubre por señales reales',
    homeDescubreTexto: 'Tus búsquedas, likes, guardados y perfiles seguidos ayudan a ordenar mejor lo que ves.',
    senalesVivas: 'Señales vivas',
    senalesTitulo: 'La portada se actualiza con la actividad real de la comunidad.',
    usuarios: 'Usuarios',
    publicaciones: 'Historias',
    comentarios: 'Comentarios',
    guardadosContador: 'Guardados',
    historiasHeroTitulo: 'Historias',
    historiasTexto: 'Un feed directo para leer publicaciones, descubrir autores y seguir conversaciones.',
    recientes: 'Recientes',
    paraTi: 'Para ti',
    siguiendo: 'Siguiendo',
    populares: 'Populares',
    cargandoHistorias: 'Cargando historias...',
    siguiendoVacioTitulo: 'Aún no sigues a nadie',
    siguiendoVacioTexto: 'Sigue autores desde su perfil para ver aquí sus publicaciones.',
    buscarTitulo: 'Buscar',
    buscarPlaceholder: 'Historias, autores o temas',
    buscarVacioTitulo: 'Empieza con una palabra',
    buscarVacioTexto: 'Busca por título, contenido, nombre de usuario o biografía.',
    buscando: 'Buscando...',
    cuentaCreada: 'Cuenta creada',
    bienvenido: 'Bienvenido de nuevo',
    usuario: 'Usuario',
    correo: 'Correo',
    usuarioOCorreo: 'Usuario o correo',
    contrasena: 'Contraseña',
    enviando: 'Enviando...',
    registrarme: 'Registrarme',
    noTienesCuenta: '¿No tienes cuenta?',
    yaTienesCuenta: '¿Ya tienes cuenta?',
    registrate: 'Regístrate',
    guardarCambios: 'Guardar cambios',
    publicacionCreada: 'Publicación creada',
    borradorGuardado: 'Borrador guardado',
    guardando: 'Guardando...',
    tituloHistoria: 'Título de la historia',
    escribeMarkdown: 'Escribe en Markdown...',
    etiquetas: 'Etiquetas',
    imagenes: 'Imágenes',
    seleccionarImagenes: 'Seleccionar imágenes',
    seleccionarFoto: 'Seleccionar foto',
    soltarImagenes: 'PNG, JPG, WEBP o GIF hasta 5 MB',
    ningunArchivo: 'Ningún archivo seleccionado',
    archivoSeleccionado: 'archivo seleccionado',
    archivosSeleccionados: 'archivos seleccionados',
    guardarBorrador: 'Guardar como borrador',
    vistaPrevia: 'Vista previa',
    contenidoPreview: 'Tu contenido aparecerá aquí.',
    paginaNoEncontrada: 'Página no encontrada',
    rutaNoExiste: 'La ruta solicitada no existe.',
    footerTexto: 'Historias, autores y conversaciones con una experiencia limpia.',
    soporte: 'Soporte',
    privacidad: 'Privacidad',
    cookies: 'Cookies',
    terminos: 'Términos'
  },
  en: {
    idioma: 'EN',
    bandera: '🇬🇧',
    idiomaNombre: 'English',
    cambiarIdioma: 'Change language',
    temaClaro: 'Light mode',
    temaOscuro: 'Dark mode',
    abrirMenu: 'Open menu',
    cerrarMenu: 'Close menu',
    buscar: 'Search',
    inicio: 'Home',
    historias: 'Stories',
    producto: 'Product',
    comunidad: 'Community',
    tendencias: 'Trends',
    creadores: 'Creators',
    escribir: 'Write',
    guardados: 'Saved',
    avisos: 'Alerts',
    perfil: 'Profile',
    salir: 'Log out',
    entrar: 'Log in',
    registrarse: 'Sign up',
    sesionCerrada: 'Session closed',
    cookiesTitulo: 'We use cookies to improve Pixara',
    cookiesTexto: 'We store preferences, language, theme and interests to sort your experience better.',
    aceptar: 'Accept',
    exploraNuevo: 'Explore what is new',
    masHistorias: 'More new stories',
    publicar: 'Publish',
    unete: 'Join',
    anterior: 'Previous',
    siguiente: 'Next',
    leerAhora: 'Read now',
    empezarAhora: 'Start now',
    heroEtiqueta: 'Pixara',
    heroTitulo: 'Social reading with calm, taste and community.',
    heroTexto: 'Pixara brings stories, profiles, saved reads and conversations into a clean experience. Discover authors, publish ideas and shape a feed that learns what you care about.',
    escribirAhora: 'Write now',
    crearCuenta: 'Create account',
    explorarHistorias: 'Explore stories',
    heroVisualEtiqueta: 'Story',
    heroVisualTitulo: 'Ideas that connect',
    heroVisualTexto: 'Posts, comments and saved reads in a clear space.',
    lecturaSocial: 'Social reading',
    historiasRecientes: 'Recent stories',
    verHistorias: 'View stories',
    comoFunciona: 'How it works',
    homeLeeTitulo: 'Read without noise',
    homeLeeTexto: 'Open, read, save and find authors without a heavy interface or unnecessary distractions.',
    homeEscribeTitulo: 'Write with context',
    homeEscribeTexto: 'Every post has a title, body, tags, conversation and profile to build an editorial presence.',
    homeDescubreTitulo: 'Discover through real signals',
    homeDescubreTexto: 'Your searches, likes, saved posts and followed profiles help sort what you see.',
    senalesVivas: 'Live signals',
    senalesTitulo: 'The front page updates with real community activity.',
    usuarios: 'Users',
    publicaciones: 'Stories',
    comentarios: 'Comments',
    guardadosContador: 'Saved',
    historiasHeroTitulo: 'Stories',
    historiasTexto: 'A direct feed for reading posts, discovering authors and following conversations.',
    recientes: 'Recent',
    paraTi: 'For you',
    siguiendo: 'Following',
    populares: 'Popular',
    cargandoHistorias: 'Loading stories...',
    siguiendoVacioTitulo: 'You are not following anyone yet',
    siguiendoVacioTexto: 'Follow authors from their profile to see their posts here.',
    buscarTitulo: 'Search',
    buscarPlaceholder: 'Stories, authors or topics',
    buscarVacioTitulo: 'Start with a word',
    buscarVacioTexto: 'Search by title, content, username or biography.',
    buscando: 'Searching...',
    cuentaCreada: 'Account created',
    bienvenido: 'Welcome back',
    usuario: 'Username',
    correo: 'Email',
    usuarioOCorreo: 'Username or email',
    contrasena: 'Password',
    enviando: 'Sending...',
    registrarme: 'Sign up',
    noTienesCuenta: 'No account yet?',
    yaTienesCuenta: 'Already have an account?',
    registrate: 'Sign up',
    guardarCambios: 'Save changes',
    publicacionCreada: 'Post created',
    borradorGuardado: 'Draft saved',
    guardando: 'Saving...',
    tituloHistoria: 'Story title',
    escribeMarkdown: 'Write in Markdown...',
    etiquetas: 'Tags',
    imagenes: 'Images',
    seleccionarImagenes: 'Select images',
    seleccionarFoto: 'Select photo',
    soltarImagenes: 'PNG, JPG, WEBP or GIF up to 5 MB',
    ningunArchivo: 'No file selected',
    archivoSeleccionado: 'file selected',
    archivosSeleccionados: 'files selected',
    guardarBorrador: 'Save as draft',
    vistaPrevia: 'Preview',
    contenidoPreview: 'Your content will appear here.',
    paginaNoEncontrada: 'Page not found',
    rutaNoExiste: 'The requested route does not exist.',
    footerTexto: 'Stories, authors and conversations with a clean experience.',
    soporte: 'Support',
    privacidad: 'Privacy',
    cookies: 'Cookies',
    terminos: 'Terms'
  }
};
