export const traducciones = {
  es: {
    idioma: 'ES',
    cambiarIdioma: 'Cambiar idioma',
    temaClaro: 'Modo claro',
    temaOscuro: 'Modo oscuro',
    abrirMenu: 'Abrir menú',
    cerrarMenu: 'Cerrar menú',
    buscar: 'Buscar',
    inicio: 'Inicio',
    historias: 'Historias',
    producto: 'Producto',
    comunidad: 'Comunidad',
    tendencias: 'Tendencias',
    creadores: 'Creadores',
    escribir: 'Escribir',
    guardados: 'Guardados',
    avisos: 'Avisos',
    perfil: 'Perfil',
    salir: 'Salir',
    entrar: 'Entrar',
    registrarse: 'Registrarse',
    sesionCerrada: 'Sesión cerrada',
    cookiesTitulo: 'Usamos cookies para mejorar Pixara',
    cookiesTexto: 'Guardamos preferencias básicas y datos de uso para que la experiencia sea más cómoda y relevante.',
    aceptar: 'Aceptar',
    exploraNuevo: 'Explora lo nuevo',
    masHistorias: 'Más historias nuevas',
    publicar: 'Publicar',
    unete: 'Únete',
    anterior: 'Anterior',
    siguiente: 'Siguiente',
    leerAhora: 'Leer ahora',
    empezarAhora: 'Empezar ahora',
    buscarTitulo: 'Buscar',
    buscarPlaceholder: 'Historias, autores o temas',
    buscarVacioTitulo: 'Empieza con una palabra',
    buscarVacioTexto: 'Busca por título, contenido, nombre de usuario o biografía.',
    buscando: 'Buscando...',
    cuentaCreada: 'Cuenta creada',
    bienvenido: 'Bienvenido de nuevo',
    crearCuenta: 'Crear cuenta',
    usuario: 'Usuario',
    correo: 'Correo',
    usuarioOCorreo: 'Usuario o correo',
    contrasena: 'Contraseña',
    enviando: 'Enviando...',
    registrarme: 'Registrarme',
    noTienesCuenta: '¿No tienes cuenta?',
    yaTienesCuenta: '¿Ya tienes cuenta?',
    registrate: 'Regístrate',
    guardarCambios: 'Guardar cambios',
    publicacionCreada: 'Publicación creada',
    borradorGuardado: 'Borrador guardado',
    guardando: 'Guardando...',
    tituloHistoria: 'Título de la historia',
    escribeMarkdown: 'Escribe en Markdown...',
    etiquetas: 'Etiquetas',
    imagenes: 'Imágenes',
    guardarBorrador: 'Guardar como borrador',
    vistaPrevia: 'Vista previa',
    contenidoPreview: 'Tu contenido aparecerá aquí.',
    paginaNoEncontrada: 'Página no encontrada',
    rutaNoExiste: 'La ruta solicitada no existe.'
  },
  en: {
    idioma: 'EN',
    cambiarIdioma: 'Change language',
    temaClaro: 'Light mode',
    temaOscuro: 'Dark mode',
    abrirMenu: 'Open menu',
    cerrarMenu: 'Close menu',
    buscar: 'Search',
    inicio: 'Home',
    historias: 'Stories',
    producto: 'Product',
    comunidad: 'Community',
    tendencias: 'Trends',
    creadores: 'Creators',
    escribir: 'Write',
    guardados: 'Saved',
    avisos: 'Alerts',
    perfil: 'Profile',
    salir: 'Log out',
    entrar: 'Log in',
    registrarse: 'Sign up',
    sesionCerrada: 'Session closed',
    cookiesTitulo: 'We use cookies to improve Pixara',
    cookiesTexto: 'We store basic preferences and usage data so the experience feels more comfortable and relevant.',
    aceptar: 'Accept',
    exploraNuevo: 'Explore what is new',
    masHistorias: 'More new stories',
    publicar: 'Publish',
    unete: 'Join',
    anterior: 'Previous',
    siguiente: 'Next',
    leerAhora: 'Read now',
    empezarAhora: 'Start now',
    buscarTitulo: 'Search',
    buscarPlaceholder: 'Stories, authors or topics',
    buscarVacioTitulo: 'Start with a word',
    buscarVacioTexto: 'Search by title, content, username or biography.',
    buscando: 'Searching...',
    cuentaCreada: 'Account created',
    bienvenido: 'Welcome back',
    crearCuenta: 'Create account',
    usuario: 'Username',
    correo: 'Email',
    usuarioOCorreo: 'Username or email',
    contrasena: 'Password',
    enviando: 'Sending...',
    registrarme: 'Sign up',
    noTienesCuenta: 'No account yet?',
    yaTienesCuenta: 'Already have an account?',
    registrate: 'Sign up',
    guardarCambios: 'Save changes',
    publicacionCreada: 'Post created',
    borradorGuardado: 'Draft saved',
    guardando: 'Saving...',
    tituloHistoria: 'Story title',
    escribeMarkdown: 'Write in Markdown...',
    etiquetas: 'Tags',
    imagenes: 'Images',
    guardarBorrador: 'Save as draft',
    vistaPrevia: 'Preview',
    contenidoPreview: 'Your content will appear here.',
    paginaNoEncontrada: 'Page not found',
    rutaNoExiste: 'The requested route does not exist.'
  }
};
